Alts registration per server
A248/LibertyBans pull request #248
Opened 2023-11-30 15:33 UTC by SnakeAmazing

This feature aims to solve a recurrent problem that was stated in the discord server multiples times. 
This problem refers to alts registration for players that haven't logged in, which means that only affects non-premium servers.

In order to solve this, I've added a way to disable alts registration per-server. This means that now you can choose which servers are going to register alts for player and which not.

Despite that, this feature hasn't been tested because I don't have the required time and resources to do it, so I'm opening this pull request in order to make more visible this new version.

So, if you are someone that needs this feature and wants to help, reach me through the libertybans discord server and I can send you the compiled version of it (you can clone this rep and compile it by yourself following the instructions).

2024-01-24 16:38 UTC, SnakeAmazing commented
Hi! Sorry for the late response. I've been a bit busy the last months. 
Thanks for the feedback, I'll have a look into solving the issues.

2024-03-05 00:09 UTC, A248 commented
Hi Snake, I've completed the heavy lifting with respect to the database queries that I described above in great detail. This means all you have to do is complete some of the lesser tasks relating to English grammar and code style, and we can merge this PR, and it will enter nonstable development builds.

At a later point in time, I will need to write additional tests for the database queries introduced by my commit. However, I don't believe that should block this PR, and I will open a separate issue for that and handle it myself. Unless you want to contribute those tests, then by all means.

2024-06-15 20:54 UTC, SrBedrock requested changes

2024-06-15 20:54 UTC, SrBedrock commented on bans-core/src/main/java/space/arim/libertybans/core/selector/EnforcementConfig.java
> +		@ConfKey("should-register-on-connection)")
remove `)` in `should-register-on-connection)`

2024-09-05 14:27 UTC, ant-7802 commented
is this releasing anytime soon?

2024-09-22 12:53 UTC, A248 commented
@ant-7802 Please upvote/follow issue #194 and you will be notified when this issue is completed.

2025-05-02 20:43 UTC, A248 commented
Hi @SnakeAmazing , please let me know if you want to finish this. Otherwise, I'll take carry of it and also conduct some tests.

2025-07-01 08:13 UTC, merged